### ISSUE TITLE
update Label for new format Smart Label

### ISSUE THREAD

**Issue by jan-kratochvil** [Salamek/PplMyApi#48]
update Label for new format Smart Label

![obrazek](https://user-images.githubusercontent.com/10809796/90380402-4831a100-e07c-11ea-99a0-ac9f92e86c9d.png)

- [x] ZPL Label
- [ ] PDF Label

**Comment by jan-kratochvil** [comment]
Will try update ZplLabel code...

**Comment by Salamek** [comment]
@jan-kratochvil PR's welcomed...

**Comment by SVNSD** [comment]
I have some work on a new label format

**Comment by jan-kratochvil** [comment]
I have prepared ZPL label, but need help. The new label includes routing label, where fields RouteCode, DepoCode, Highlighted are needed. These fields can be obtained from API call GetCitiesRouting with parameters CountryCode, ZipCode, Street (new parameter).

The questions is how to implement it in this library.

The function generateLabel has only parameter package, so new parameters could be added, or these properties could be included in Package object and inicialized by the constructor automatically?

I'm sort of lost...

**Comment by Salamek** [comment]
I think that this will require a new class eg. `RoutedPackage extends Package` that will have package and routingInfo as required arguments in constructor... and Label generators will require RoutedPackege instead of simple Package...
OFC this is BC break but well... (that is only my wild guess i need to look on it deeper when i'm not on vacation)

BUT FIRST i noticed there is a method called `CreatePackageLabel` in `https://myapi.ppl.cz/MyAPI.svc?singleWsdl` maybe would be a good idea to explore that first, if it works we could deprecate current label generators and just redirect PPL(People) to use that method. Only down/upside is that we will lose our (obsolete) custom label generator...

**Comment by jan-kratochvil** [comment]
I asked about the method CreatePackageLabel PPL people and the info is that its not implemented yet. May be in future. Now we have to create by ourselfs.

**Comment by kibkib** [comment]
Is there the ZPL label of new format available please?

**Comment by jan-kratochvil** [comment]
I have it, will try pull request.

**Comment by jan-kratochvil** [comment]
But I only have the ZPL version, no PDF. Someone else will have to work on that.

**Comment by kibkib** [comment]
That would be great, ZPL is ok for me. Please open the pull request.

**Comment by kibkib** [comment]
> I have it, will try pull request.

Will you please publish the new ZPL label? Do you use it currently and PPL accept it? Thank you

**Comment by jan-kratochvil** [comment]
PR created

**Comment by hary28** [comment]
PR for PDF smart label created.
